// Code generated by qtc from "admin_agents_add_new.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/admin_agents_add_new.qtpl:1
package templates

//line templates/admin_agents_add_new.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/admin_agents_add_new.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/admin_agents_add_new.qtpl:2
type AdminAgentsAddNew struct {
	Agent        AdminAgentsAddAgent
	ErrorMessage string
}

//line templates/admin_agents_add_new.qtpl:8
func (p *AdminAgentsAddNew) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/admin_agents_add_new.qtpl:8
	qw422016.N().S(`Confirm | Add a new instance`)
//line templates/admin_agents_add_new.qtpl:8
}

//line templates/admin_agents_add_new.qtpl:8
func (p *AdminAgentsAddNew) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/admin_agents_add_new.qtpl:8
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/admin_agents_add_new.qtpl:8
	p.StreamTitle(qw422016)
//line templates/admin_agents_add_new.qtpl:8
	qt422016.ReleaseWriter(qw422016)
//line templates/admin_agents_add_new.qtpl:8
}

//line templates/admin_agents_add_new.qtpl:8
func (p *AdminAgentsAddNew) Title() string {
//line templates/admin_agents_add_new.qtpl:8
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/admin_agents_add_new.qtpl:8
	p.WriteTitle(qb422016)
//line templates/admin_agents_add_new.qtpl:8
	qs422016 := string(qb422016.B)
//line templates/admin_agents_add_new.qtpl:8
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/admin_agents_add_new.qtpl:8
	return qs422016
//line templates/admin_agents_add_new.qtpl:8
}

//line templates/admin_agents_add_new.qtpl:9
func (p *AdminAgentsAddNew) StreamBody(qw422016 *qt422016.Writer) {
//line templates/admin_agents_add_new.qtpl:9
	qw422016.N().S(`
		<p><a href="/admin/" title="Administration">Administration</a> / <a href="/admin/agents/" title="Agents">Agents</a> / <a href="/admin/agents/add/" title="Add a new agents">Add a new agents</a> / Confirm</p>
		<hr>
		<h2>Add a new agent</h2>
		<h3>Confirm</h3>
		`)
//line templates/admin_agents_add_new.qtpl:14
	if p.HasError() {
//line templates/admin_agents_add_new.qtpl:14
		qw422016.N().S(`
		<p>`)
//line templates/admin_agents_add_new.qtpl:15
		qw422016.E().S(p.Error())
//line templates/admin_agents_add_new.qtpl:15
		qw422016.N().S(`</p>
		`)
//line templates/admin_agents_add_new.qtpl:16
	} else {
//line templates/admin_agents_add_new.qtpl:16
		qw422016.N().S(`
		<p>Are you sure you want to add this agent <strong>`)
//line templates/admin_agents_add_new.qtpl:17
		qw422016.E().S(p.Agent.Name)
//line templates/admin_agents_add_new.qtpl:17
		qw422016.N().S(`</strong>, to be managed by this system?</p>
		<table>
			<tr>
				<td>Name</td>
				<td>`)
//line templates/admin_agents_add_new.qtpl:21
		qw422016.E().S(p.Agent.Name)
//line templates/admin_agents_add_new.qtpl:21
		qw422016.N().S(`</td>
			</tr>
			<tr>
				<td>Hostname</td>
				<td>`)
//line templates/admin_agents_add_new.qtpl:25
		qw422016.E().S(p.Agent.Hostname)
//line templates/admin_agents_add_new.qtpl:25
		qw422016.N().S(`:`)
//line templates/admin_agents_add_new.qtpl:25
		qw422016.E().S(p.Agent.Port)
//line templates/admin_agents_add_new.qtpl:25
		qw422016.N().S(`</td>
			</tr>
			<tr>
				<td>Version</td>
				<td>`)
//line templates/admin_agents_add_new.qtpl:29
		qw422016.E().S(p.Agent.Version)
//line templates/admin_agents_add_new.qtpl:29
		qw422016.N().S(`</td>
			</tr>
		</table>
		<form method="post" action="/admin/agents/add/new/">
			<input type="hidden" name="agent_name" value="`)
//line templates/admin_agents_add_new.qtpl:33
		qw422016.E().S(p.Agent.Name)
//line templates/admin_agents_add_new.qtpl:33
		qw422016.N().S(`">
			<input type="hidden" name="agent_hostname" value="`)
//line templates/admin_agents_add_new.qtpl:34
		qw422016.E().S(p.Agent.Hostname)
//line templates/admin_agents_add_new.qtpl:34
		qw422016.N().S(`">
			<input type="hidden" name="agent_port" value="`)
//line templates/admin_agents_add_new.qtpl:35
		qw422016.E().S(p.Agent.Port)
//line templates/admin_agents_add_new.qtpl:35
		qw422016.N().S(`">
			<input type="hidden" name="creation_confirm" value="`)
//line templates/admin_agents_add_new.qtpl:36
		qw422016.E().S(p.Agent.Confirmed)
//line templates/admin_agents_add_new.qtpl:36
		qw422016.N().S(`">
			<p><input type="submit" value="Add"></p>
		</form>
		`)
//line templates/admin_agents_add_new.qtpl:39
	}
//line templates/admin_agents_add_new.qtpl:39
	qw422016.N().S(`
`)
//line templates/admin_agents_add_new.qtpl:40
}

//line templates/admin_agents_add_new.qtpl:40
func (p *AdminAgentsAddNew) WriteBody(qq422016 qtio422016.Writer) {
//line templates/admin_agents_add_new.qtpl:40
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/admin_agents_add_new.qtpl:40
	p.StreamBody(qw422016)
//line templates/admin_agents_add_new.qtpl:40
	qt422016.ReleaseWriter(qw422016)
//line templates/admin_agents_add_new.qtpl:40
}

//line templates/admin_agents_add_new.qtpl:40
func (p *AdminAgentsAddNew) Body() string {
//line templates/admin_agents_add_new.qtpl:40
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/admin_agents_add_new.qtpl:40
	p.WriteBody(qb422016)
//line templates/admin_agents_add_new.qtpl:40
	qs422016 := string(qb422016.B)
//line templates/admin_agents_add_new.qtpl:40
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/admin_agents_add_new.qtpl:40
	return qs422016
//line templates/admin_agents_add_new.qtpl:40
}

//line templates/admin_agents_add_new.qtpl:42
func (p *AdminAgentsAddNew) HasError() bool {
	return len(p.ErrorMessage) > 0
}

//line templates/admin_agents_add_new.qtpl:46
func (p *AdminAgentsAddNew) StreamError(qw422016 *qt422016.Writer) {
//line templates/admin_agents_add_new.qtpl:46
	qw422016.E().S(p.ErrorMessage)
//line templates/admin_agents_add_new.qtpl:46
}

//line templates/admin_agents_add_new.qtpl:46
func (p *AdminAgentsAddNew) WriteError(qq422016 qtio422016.Writer) {
//line templates/admin_agents_add_new.qtpl:46
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/admin_agents_add_new.qtpl:46
	p.StreamError(qw422016)
//line templates/admin_agents_add_new.qtpl:46
	qt422016.ReleaseWriter(qw422016)
//line templates/admin_agents_add_new.qtpl:46
}

//line templates/admin_agents_add_new.qtpl:46
func (p *AdminAgentsAddNew) Error() string {
//line templates/admin_agents_add_new.qtpl:46
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/admin_agents_add_new.qtpl:46
	p.WriteError(qb422016)
//line templates/admin_agents_add_new.qtpl:46
	qs422016 := string(qb422016.B)
//line templates/admin_agents_add_new.qtpl:46
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/admin_agents_add_new.qtpl:46
	return qs422016
//line templates/admin_agents_add_new.qtpl:46
}
