// Code generated by qtc from "admin_index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/admin_index.qtpl:1
package templates

//line templates/admin_index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/admin_index.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/admin_index.qtpl:2
type AdminIndex struct {
	ErrorMessage string
}

//line templates/admin_index.qtpl:7
func (p *AdminIndex) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/admin_index.qtpl:7
	qw422016.N().S(`Administration`)
//line templates/admin_index.qtpl:7
}

//line templates/admin_index.qtpl:7
func (p *AdminIndex) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/admin_index.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/admin_index.qtpl:7
	p.StreamTitle(qw422016)
//line templates/admin_index.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line templates/admin_index.qtpl:7
}

//line templates/admin_index.qtpl:7
func (p *AdminIndex) Title() string {
//line templates/admin_index.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/admin_index.qtpl:7
	p.WriteTitle(qb422016)
//line templates/admin_index.qtpl:7
	qs422016 := string(qb422016.B)
//line templates/admin_index.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/admin_index.qtpl:7
	return qs422016
//line templates/admin_index.qtpl:7
}

//line templates/admin_index.qtpl:8
func (p *AdminIndex) StreamBody(qw422016 *qt422016.Writer) {
//line templates/admin_index.qtpl:8
	qw422016.N().S(`
		<p><a href="/admin/" title="Administration">Administration</a> / </p>
		<hr>
		<h2>Administration</h2>
		`)
//line templates/admin_index.qtpl:12
	if p.HasError() {
//line templates/admin_index.qtpl:12
		qw422016.N().S(`<p>`)
//line templates/admin_index.qtpl:12
		p.StreamError(qw422016)
//line templates/admin_index.qtpl:12
		qw422016.N().S(`</p>`)
//line templates/admin_index.qtpl:12
	}
//line templates/admin_index.qtpl:12
	qw422016.N().S(`
		<ol>
			<li><a href="/admin/agents/" title="Agents">Agents</a></li>
		</ol>
`)
//line templates/admin_index.qtpl:16
}

//line templates/admin_index.qtpl:16
func (p *AdminIndex) WriteBody(qq422016 qtio422016.Writer) {
//line templates/admin_index.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/admin_index.qtpl:16
	p.StreamBody(qw422016)
//line templates/admin_index.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line templates/admin_index.qtpl:16
}

//line templates/admin_index.qtpl:16
func (p *AdminIndex) Body() string {
//line templates/admin_index.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/admin_index.qtpl:16
	p.WriteBody(qb422016)
//line templates/admin_index.qtpl:16
	qs422016 := string(qb422016.B)
//line templates/admin_index.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/admin_index.qtpl:16
	return qs422016
//line templates/admin_index.qtpl:16
}

//line templates/admin_index.qtpl:18
func (p *AdminIndex) HasError() bool {
	return len(p.ErrorMessage) > 0
}

//line templates/admin_index.qtpl:22
func (p *AdminIndex) StreamError(qw422016 *qt422016.Writer) {
//line templates/admin_index.qtpl:22
	qw422016.E().S(p.ErrorMessage)
//line templates/admin_index.qtpl:22
}

//line templates/admin_index.qtpl:22
func (p *AdminIndex) WriteError(qq422016 qtio422016.Writer) {
//line templates/admin_index.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/admin_index.qtpl:22
	p.StreamError(qw422016)
//line templates/admin_index.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line templates/admin_index.qtpl:22
}

//line templates/admin_index.qtpl:22
func (p *AdminIndex) Error() string {
//line templates/admin_index.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/admin_index.qtpl:22
	p.WriteError(qb422016)
//line templates/admin_index.qtpl:22
	qs422016 := string(qb422016.B)
//line templates/admin_index.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/admin_index.qtpl:22
	return qs422016
//line templates/admin_index.qtpl:22
}
