// Code generated by qtc from "admin_agents_add.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/admin_agents_add.qtpl:1
package templates

//line templates/admin_agents_add.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/admin_agents_add.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/admin_agents_add.qtpl:2
type AdminAgentsAdd struct {
	Agent        AdminAgentsAddAgent
	ErrorMessage string
}

//line templates/admin_agents_add.qtpl:8
type AdminAgentsAddAgent struct {
	Name      string
	Hostname  string
	Port      string
	Version   string
	Confirmed string
}

//line templates/admin_agents_add.qtpl:17
func (p *AdminAgentsAdd) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/admin_agents_add.qtpl:17
	qw422016.N().S(`Add a new agent`)
//line templates/admin_agents_add.qtpl:17
}

//line templates/admin_agents_add.qtpl:17
func (p *AdminAgentsAdd) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/admin_agents_add.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/admin_agents_add.qtpl:17
	p.StreamTitle(qw422016)
//line templates/admin_agents_add.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line templates/admin_agents_add.qtpl:17
}

//line templates/admin_agents_add.qtpl:17
func (p *AdminAgentsAdd) Title() string {
//line templates/admin_agents_add.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/admin_agents_add.qtpl:17
	p.WriteTitle(qb422016)
//line templates/admin_agents_add.qtpl:17
	qs422016 := string(qb422016.B)
//line templates/admin_agents_add.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/admin_agents_add.qtpl:17
	return qs422016
//line templates/admin_agents_add.qtpl:17
}

//line templates/admin_agents_add.qtpl:18
func (p *AdminAgentsAdd) StreamBody(qw422016 *qt422016.Writer) {
//line templates/admin_agents_add.qtpl:18
	qw422016.N().S(`
		<p><a href="/admin/" title="Administration">Administration</a> / <a href="/admin/agents/" title="Agents">Agents</a> / <a href="/admin/agents/add/" title="Add a new agent">Add a new agent</a> / </p>
		<hr>
		<h2>Add a new agent</h2>
		`)
//line templates/admin_agents_add.qtpl:22
	if p.HasError() {
//line templates/admin_agents_add.qtpl:22
		qw422016.N().S(`<p>`)
//line templates/admin_agents_add.qtpl:22
		p.StreamError(qw422016)
//line templates/admin_agents_add.qtpl:22
		qw422016.N().S(`</p>`)
//line templates/admin_agents_add.qtpl:22
	}
//line templates/admin_agents_add.qtpl:22
	qw422016.N().S(`
		<form method="post" action="/admin/agents/add/new/">
			<p>
				<label for="agent_hostname">Hostname</label>
				<br>
				<input type="text" name="agent_hostname" value="`)
//line templates/admin_agents_add.qtpl:27
	qw422016.E().S(p.Agent.Hostname)
//line templates/admin_agents_add.qtpl:27
	qw422016.N().S(`" placeholder="localhost">
			</p>
			<p>
				<label for="agent_port">Port</label>
				<br>
				<input type="text" name="agent_port" value="`)
//line templates/admin_agents_add.qtpl:32
	qw422016.E().S(p.Agent.Port)
//line templates/admin_agents_add.qtpl:32
	qw422016.N().S(`" placeholder="9091">
			</p>
			<input type="hidden" name="creation_confirm" value="`)
//line templates/admin_agents_add.qtpl:34
	qw422016.E().S(p.Agent.Confirmed)
//line templates/admin_agents_add.qtpl:34
	qw422016.N().S(`">
			<p><input type="submit" value="Add"></p>
		</form>
`)
//line templates/admin_agents_add.qtpl:37
}

//line templates/admin_agents_add.qtpl:37
func (p *AdminAgentsAdd) WriteBody(qq422016 qtio422016.Writer) {
//line templates/admin_agents_add.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/admin_agents_add.qtpl:37
	p.StreamBody(qw422016)
//line templates/admin_agents_add.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line templates/admin_agents_add.qtpl:37
}

//line templates/admin_agents_add.qtpl:37
func (p *AdminAgentsAdd) Body() string {
//line templates/admin_agents_add.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/admin_agents_add.qtpl:37
	p.WriteBody(qb422016)
//line templates/admin_agents_add.qtpl:37
	qs422016 := string(qb422016.B)
//line templates/admin_agents_add.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/admin_agents_add.qtpl:37
	return qs422016
//line templates/admin_agents_add.qtpl:37
}

//line templates/admin_agents_add.qtpl:39
func (p *AdminAgentsAdd) HasError() bool {
	return len(p.ErrorMessage) > 0
}

//line templates/admin_agents_add.qtpl:43
func (p *AdminAgentsAdd) StreamError(qw422016 *qt422016.Writer) {
//line templates/admin_agents_add.qtpl:43
	qw422016.E().S(p.ErrorMessage)
//line templates/admin_agents_add.qtpl:43
}

//line templates/admin_agents_add.qtpl:43
func (p *AdminAgentsAdd) WriteError(qq422016 qtio422016.Writer) {
//line templates/admin_agents_add.qtpl:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/admin_agents_add.qtpl:43
	p.StreamError(qw422016)
//line templates/admin_agents_add.qtpl:43
	qt422016.ReleaseWriter(qw422016)
//line templates/admin_agents_add.qtpl:43
}

//line templates/admin_agents_add.qtpl:43
func (p *AdminAgentsAdd) Error() string {
//line templates/admin_agents_add.qtpl:43
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/admin_agents_add.qtpl:43
	p.WriteError(qb422016)
//line templates/admin_agents_add.qtpl:43
	qs422016 := string(qb422016.B)
//line templates/admin_agents_add.qtpl:43
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/admin_agents_add.qtpl:43
	return qs422016
//line templates/admin_agents_add.qtpl:43
}
