// Code generated by qtc from "base.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/base.qtpl:1
package templates

//line templates/base.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/base.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/base.qtpl:2
type Page interface {
//line templates/base.qtpl:2
	Title() string
//line templates/base.qtpl:2
	StreamTitle(qw422016 *qt422016.Writer)
//line templates/base.qtpl:2
	WriteTitle(qq422016 qtio422016.Writer)
//line templates/base.qtpl:2
	Body() string
//line templates/base.qtpl:2
	StreamBody(qw422016 *qt422016.Writer)
//line templates/base.qtpl:2
	WriteBody(qq422016 qtio422016.Writer)
//line templates/base.qtpl:2
	Error() string
//line templates/base.qtpl:2
	StreamError(qw422016 *qt422016.Writer)
//line templates/base.qtpl:2
	WriteError(qq422016 qtio422016.Writer)
//line templates/base.qtpl:2
}

//line templates/base.qtpl:9
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line templates/base.qtpl:9
	qw422016.N().S(`
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>`)
//line templates/base.qtpl:14
	p.StreamTitle(qw422016)
//line templates/base.qtpl:14
	qw422016.N().S(` | dhcpdadm</title>
		<link rel="stylesheet" href="/css/style.css">
	</head>
	<body>
		<header>
			<h1>dhcpdadm</h1>
			<hr>
		</header>
		<nav>
			<ol>
				<li><a href="/" title="Home">Home</a></li>
				<li><a href="/admin/" title="Administration">Administration</a></li>
				<li>
					<ol>
						<li><a href="/admin/agents/" title="Agents">Agents</a></li>
						<li>
							<ol>
								<li><a href="/admin/agents/add/" title="Add a new agent">Add a new agent</a></li>
							</ol>
						</li>
					</ol>
				</li>
			</ol>
		</nav>
		<main>
			`)
//line templates/base.qtpl:39
	p.StreamBody(qw422016)
//line templates/base.qtpl:39
	qw422016.N().S(`
		</main>
		<footer>
			<hr>
			<p>dhcpdadm</p>
		</footer>
	</body>
</html>
`)
//line templates/base.qtpl:47
}

//line templates/base.qtpl:47
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line templates/base.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/base.qtpl:47
	StreamPageTemplate(qw422016, p)
//line templates/base.qtpl:47
	qt422016.ReleaseWriter(qw422016)
//line templates/base.qtpl:47
}

//line templates/base.qtpl:47
func PageTemplate(p Page) string {
//line templates/base.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/base.qtpl:47
	WritePageTemplate(qb422016, p)
//line templates/base.qtpl:47
	qs422016 := string(qb422016.B)
//line templates/base.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/base.qtpl:47
	return qs422016
//line templates/base.qtpl:47
}

//line templates/base.qtpl:49
type BasePage struct{}

//line templates/base.qtpl:50
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/base.qtpl:50
	qw422016.N().S(`This is a base title`)
//line templates/base.qtpl:50
}

//line templates/base.qtpl:50
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/base.qtpl:50
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/base.qtpl:50
	p.StreamTitle(qw422016)
//line templates/base.qtpl:50
	qt422016.ReleaseWriter(qw422016)
//line templates/base.qtpl:50
}

//line templates/base.qtpl:50
func (p *BasePage) Title() string {
//line templates/base.qtpl:50
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/base.qtpl:50
	p.WriteTitle(qb422016)
//line templates/base.qtpl:50
	qs422016 := string(qb422016.B)
//line templates/base.qtpl:50
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/base.qtpl:50
	return qs422016
//line templates/base.qtpl:50
}

//line templates/base.qtpl:51
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/base.qtpl:51
	qw422016.N().S(`This is a base body`)
//line templates/base.qtpl:51
}

//line templates/base.qtpl:51
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/base.qtpl:51
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/base.qtpl:51
	p.StreamBody(qw422016)
//line templates/base.qtpl:51
	qt422016.ReleaseWriter(qw422016)
//line templates/base.qtpl:51
}

//line templates/base.qtpl:51
func (p *BasePage) Body() string {
//line templates/base.qtpl:51
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/base.qtpl:51
	p.WriteBody(qb422016)
//line templates/base.qtpl:51
	qs422016 := string(qb422016.B)
//line templates/base.qtpl:51
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/base.qtpl:51
	return qs422016
//line templates/base.qtpl:51
}

//line templates/base.qtpl:52
func (p *BasePage) StreamError(qw422016 *qt422016.Writer) {
//line templates/base.qtpl:52
}

//line templates/base.qtpl:52
func (p *BasePage) WriteError(qq422016 qtio422016.Writer) {
//line templates/base.qtpl:52
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/base.qtpl:52
	p.StreamError(qw422016)
//line templates/base.qtpl:52
	qt422016.ReleaseWriter(qw422016)
//line templates/base.qtpl:52
}

//line templates/base.qtpl:52
func (p *BasePage) Error() string {
//line templates/base.qtpl:52
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/base.qtpl:52
	p.WriteError(qb422016)
//line templates/base.qtpl:52
	qs422016 := string(qb422016.B)
//line templates/base.qtpl:52
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/base.qtpl:52
	return qs422016
//line templates/base.qtpl:52
}
